// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: user.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DbName        string                 `protobuf:"bytes,2,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	DbPinHash     string                 `protobuf:"bytes,3,opt,name=db_pin_hash,json=dbPinHash,proto3" json:"db_pin_hash,omitempty"`
	DbUnshashPin  string                 `protobuf:"bytes,4,opt,name=db_unshash_pin,json=dbUnshashPin,proto3" json:"db_unshash_pin,omitempty"`
	DbEmail       string                 `protobuf:"bytes,5,opt,name=db_email,json=dbEmail,proto3" json:"db_email,omitempty"`
	CardAtr       string                 `protobuf:"bytes,6,opt,name=card_atr,json=cardAtr,proto3" json:"card_atr,omitempty"`
	SerialNumber  string                 `protobuf:"bytes,7,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	DbUserSign    bool                   `protobuf:"varint,8,opt,name=db_user_sign,json=dbUserSign,proto3" json:"db_user_sign,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *User) GetDbPinHash() string {
	if x != nil {
		return x.DbPinHash
	}
	return ""
}

func (x *User) GetDbUnshashPin() string {
	if x != nil {
		return x.DbUnshashPin
	}
	return ""
}

func (x *User) GetDbEmail() string {
	if x != nil {
		return x.DbEmail
	}
	return ""
}

func (x *User) GetCardAtr() string {
	if x != nil {
		return x.CardAtr
	}
	return ""
}

func (x *User) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *User) GetDbUserSign() bool {
	if x != nil {
		return x.DbUserSign
	}
	return false
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\"\x91\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\adb_name\x18\x02 \x01(\tR\x06dbName\x12\x1e\n" +
	"\vdb_pin_hash\x18\x03 \x01(\tR\tdbPinHash\x12$\n" +
	"\x0edb_unshash_pin\x18\x04 \x01(\tR\fdbUnshashPin\x12\x19\n" +
	"\bdb_email\x18\x05 \x01(\tR\adbEmail\x12\x19\n" +
	"\bcard_atr\x18\x06 \x01(\tR\acardAtr\x12#\n" +
	"\rserial_number\x18\a \x01(\tR\fserialNumber\x12 \n" +
	"\fdb_user_sign\x18\b \x01(\bR\n" +
	"dbUserSign\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt26\n" +
	"\vUserService\x12'\n" +
	"\tSyncUsers\x12\n" +
	".user.User\x1a\n" +
	".user.User(\x010\x01BFZDgithub.com/BillyLouis/grpc_with_mtls/cmd/grpc_with_mtls/proto/userpbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_user_proto_goTypes = []any{
	(*User)(nil), // 0: user.User
}
var file_user_proto_depIdxs = []int32{
	0, // 0: user.UserService.SyncUsers:input_type -> user.User
	0, // 1: user.UserService.SyncUsers:output_type -> user.User
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
